#!/bin/zsh

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

for dotfile in $( ls $DIR ); do
	if [ -f $dotfile ]; then
		if [[ $dotfile == *.dotfile ]]
		then
			newdotfilename=$(basename "$dotfile")
			newdotfilename="${newdotfilename%.*}"
			ln -sf $DIR/$dotfile ~/.$newdotfilename
			echo symlinked ~/.$newdotfilename
		fi
	fi
done
